name: Test Build on Ubuntu

on:
  push:
    branches:
      - '**'  # Run on every push to any branch
  pull_request:
    branches:
      - '**'  # Run on every pull request to any branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install CMake and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential

    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        make
        echo "Build completed successfully."
        echo "Testing build output"
        make run
